kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: nginx-static-app-deploy-pipeline
spec:
  source:
    type: Git
    git:
      uri: https://github.com/leprechaun/nginx-static-app-on-openshift
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: ./Jenkinsfile-deploy
