---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-static-app
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: nginx-static-app.kubernetes.fscker.org
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-static-app
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-static-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: nginx-static-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-static-app
spec:
  replicas: 1
  selector:
    matchLabels:
        app: nginx-static-app
  template:
    metadata:
      labels:
        app: nginx-static-app
    spec:
      containers:
        - name: nginx
          image: leprechaun/nginx-static-app-on-k8s:${REF}
          ports:
          - name: http
            containerPort: 8080
