apiVersion: v1
kind: DeploymentConfig
metadata:
  name: nginx-static-app
  labels:
    app: nginx-static-app
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1
  selector:
    app: nginx
    deploymentconfig: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-static-app
        deploymentconfig: nginx-static-app
    spec:
      containers:
        - name: nginx
          image: >-
            172.30.1.1:5000/my-project/nginx-static-app
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
