apiVersion: v1
kind: Service
metadata:
  name: nginx-static-app
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    deploymentconfig: nginx-static-app
  type: ClusterIP
  sessionAffinity: None
