pipelines:
  nginx-static-app-build:
    group: nginx-static-app
    label_template: "${git[:8]}"
    locking: "on"
    timer:
      spec: "* * * * * ? *"
      only_on_changes: yes
    materials:
      git:
        git: https://github.com/leprechaun/nginx-static-app-on-k8s.git
        branch: master
        auto_update: true
        shallow_clone: true
      nginx:
        pipeline: nginx-on-openshift-build
        stage: build-image

    stages:
      - build-image:
          tasks:
            - script: |
                docker build -t registry.k8s.fscker.org:80/leprechaun/nginx-static-app-on-k8s \
                  --label git-commit=${GO_REVISION_GIT} \
                  --label git-repo=git@github.com/leprechaun/nginx-static-app-on-k8s \
                  --label go-pipeline=${GO_PIPELINE_NAME} \
                  --label go-pipeline-counter=${GO_PIPELINE_COUNTER} \
                  --label go-pipeline-stage=${GO_STAGE_NAME} \
                  --label go-pipeline-stage-counter=${GO_STAGE_COUNTER} \
                  --label go-pipeline-job=${GO_JOB_NAME} \
                  .
            - script: |
                docker push registry.k8s.fscker.org:80/leprechaun/nginx-static-app-on-k8s
